### ISSUE TITLE
[Feature] Possibility to edit sources

### ISSUE THREAD

**Issue by Dranixx** [tmdict/mhy-notes#1]
Hello, Is there a reason for not be able to add a source to a build ?

**Comment by slsdo** [comment]
@Dranixx mostly just never got around to it as there didn't seem to be a lot of folks using the feature, I can certainly add it in a future update if there's enough interest :)

**Comment by slsdo** [comment]
You should be able to add Sources to new or copied builds via the "Submitted By" input.

To add sources to existing builds, either submit a PR request to update them ([like here](https://github.com/tmdict/genshin-tldr/blob/main/data/builds/albedo.sub-dps.yml#L49-L52), for example) or make a copy of the existing build and add your own sources (these "new" builds will have a permalink you could use to share with others).
