### ISSUE TITLE
"For the Love of Godwin" outdated description

### ISSUE THREAD

**Issue by Seeker14491** [tmdict/mhy-notes#2]
For the Mondstadt achievement "For the Love of Godwin", it currently states that giving Dandelion Seeds directly from the inventory doesn't progress the achievement. This used to be the case, but it was fixed some time before 3.0 (I don't know what version). Giving seeds from the inventory progresses the achievement now. This is noted on [the achievement wiki page](https://genshin-impact.fandom.com/wiki/For_the_Love_of_Godwin), and I also just verified it on my account.

**Comment by slsdo** [comment]
@Seeker14491 thanks for the heads up! I've updated the description to reflect the change :)
