### ISSUE TITLE
Outdated Cliffhanger commission achievement descriptions

### ISSUE THREAD

**Issue by Seeker14491** [tmdict/mhy-notes#3]
The description of the two Liyue achievements "Friends, Travelers, Lend Me Your Ears..." and "Once Upon a Time..." are outdated. Since game version 3.5, all three NPCs always appear, instead of two random ones.

https://genshin-impact.fandom.com/wiki/Cliffhanger#Change_History

**Comment by slsdo** [comment]
The descriptions have been updated, thanks for the feedback! https://github.com/tmdict/mhy-notes/commit/8489ef9ec166c4e531a2d0645a59f27e933b460d

**Comment by Seeker14491** [comment]
A tiny nit: In the sentence

```
After giving one excerpt to Liu Su, the other excerpt will remain in your inventory and can be used during future commissions.
```

`excerpt` should now be plural `excerpts`, since you will turn one in and have two left over.

**edit:** or maybe just remove that part. You always get all three excerpts, so there's not really any point in saying you can use them in future commisions, since you will again get all three in the future anyways.

**Comment by slsdo** [comment]
Very good point, I've gone ahead and removed it since the extra information is a redundant now that the commission has been optimized.
