### ISSUE TITLE
xianyun artifact main stat

### ISSUE THREAD

**Issue by wassmansdorff** [tmdict/mhy-notes#4]
hi, on your website it says xianyun's reccomended arti main stats for sands is ER%, but ATK% is easily better if you get some ER% from substats. as for circlet it recommends heal% which is blatantly wrong, it's ATK%

thanks!

**Comment by slsdo** [comment]
Thanks for the feedback! The heal% came from the original source, which admittedly can be mistaken sometimes. I've updated the mainstat info to reflect the important of ATK%.
